### ISSUE TITLE
$filter with numeric value work only with integer

### ISSUE THREAD

**Issue by bonfi7** [OData/WebApi#2216]
An HTTP OData V4 request using a filter with the eq operator with numeric value different from int (i.e. decimal, double) fails.

Custom endpoint:
$filter=Quantity eq 300

Error:
Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer|Connection ID "18302628895834243116", Request ID "80000032-0002-fe00-b63f-84710c7967bb": An unhandled exception was thrown by the application. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidCastException: Unable to cast object of type 'System.Double' to type 'System.Nullable`1[System.Int32]'.
   at lambda_method(Closure , DataItem )
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Linq.Enumerable.LongCount[TSource](IEnumerable`1 source)
   at System.Linq.EnumerableExecutor`1.Execute()
   at System.Linq.EnumerableQuery`1.System.Linq.IQueryProvider.Execute[TElement](Expression expression)
   at System.Linq.Queryable.LongCount[TSource](IQueryable`1 source)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.AspNet.OData.ExpressionHelpers.<>c__DisplayClass0_0.<Count>b__0()
   at Microsoft.AspNet.OData.ODataFeature.get_TotalCount()
   at Microsoft.AspNet.OData.Adapters.WebApiContext.get_TotalCount()
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSetSerializer.CreateResourceSet(IEnumerable resourceSetInstance, IEdmCollectionTypeReference resourceSetType, ODataSerializerContext writeContext)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteResourceSet(IEnumerable enumerable, IEdmTypeReference resourceSetType, ODataWriter writer, ODataSerializerContext writeContext)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteObjectInline(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext)
   at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteObject(Object graph, Type type, ODataMessageWriter messageWriter, ODataSerializerContext writeContext)
   at Microsoft.AspNet.OData.Formatter.ODataOutputFormatterHelper.WriteToStream(Type type, Object value, IEdmModel model, ODataVersion version, Uri baseAddress, MediaTypeHeaderValue contentType, IWebApiUrlHelper internaUrlHelper, IWebApiRequestMessage internalRequest, IWebApiHeaders internalRequestHeaders, Func`2 getODataMessageWrapper, Func`2 getEdmTypeSerializer, Func`2 getODataPayloadSerializer, Func`1 getODataSerializerContext)
   at Microsoft.AspNet.OData.Formatter.ODataOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()

Additional detail:
Microsoft.AspNetCore.OData, Version=7.4.1.0
.NET Core 3.1.0
I have also tried to format filter value according to EDM type(i.e. 300.0M) but it seems to ignore the value. 

Expected behaviour:
The API returns a list of values meeting filter criteria & does not throws an error.

**Comment by xuzhg** [comment]
@bonfi7 Would you please share us an repro or your config and your model?

**Comment by bonfi7** [comment]
@xuzhg Hi, 
there my configuration. I have a dynamic model because in my environment and user can specify a SQL query and retrieve dynamically the result. 


`public class EntitiesController : ODataController
{
	private IDataProvider _service;
	public string _entity { get { return Request.Query["entity"].ToString(); } }
	public EntitiesController(ICacheService service)
	{
		_service = service;
	}
	
	[EnableQuery]
	public IActionResult Get()
	{
		var data = _service.GetData(_entity);
		return Ok(data?.AsQueryable());
	}
	
	[EnableQuery]
	public IActionResult GetEntity(string entity)
	{            
		if (string.IsNullOrEmpty(entity))
		{
			return BadRequest();
		}
		var data = _service.GetData(entity);
		return Ok(data?.AsQueryable());
	}
}


public interface IDataProvider
{
    List<DataItem> GetData(string entity);    
}

public class DataItem
{
    public DataItem()
    {
        __id = null;
    }
    public int? __id { get; set; }
    public IDictionary<string, object> DynamicProperties { get; set; }
}


public class Startup
{
    public IConfiguration Configuration { get; }

    public Startup(IConfiguration configuration)
    {
        Configuration = configuration;            
    }

    // This method gets called by the runtime. Use this method to add services to the container.
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddResponseCompression();

        services.AddSession(options =>
        {
            options.IdleTimeout = TimeSpan.FromMinutes(20);//You can set Time  
            options.Cookie.IsEssential = true;
        });

        services.AddControllersWithViews(options =>
        {
            options.RespectBrowserAcceptHeader = true;
        })
        .AddXmlSerializerFormatters()
        .SetCompatibilityVersion(CompatibilityVersion.Version_3_0);

        // In production, the Angular files will be served from this directory
        services.AddSpaStaticFiles(configuration =>
        {
            configuration.RootPath = "ClientApp/dist";
        });

        services.AddControllers(mvcOptions =>
            mvcOptions.EnableEndpointRouting = false);

        services.AddOData();

        services.AddCors(o => o.AddPolicy("AllowAny", builder =>
        {
            builder.AllowAnyOrigin()
                   .AllowAnyMethod()
                   .AllowAnyHeader();
        }));

        
        services.AddScoped<IDataProvider, DataProvider>();
    }

    // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
    public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
    {
        if (env.IsDevelopment())
        {
            IdentityModelEventSource.ShowPII = true;
            app.UseDeveloperExceptionPage();
        }
        else
        {
            app.UseExceptionHandler("/Error");
            // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
            app.UseHsts();
            app.UseHttpsRedirection();
        }

        app.UseStaticFiles();
        if (!env.IsDevelopment())
        {
            app.UseSpaStaticFiles();
        }

        app.UseResponseCompression();

        app.UseSession();
        app.UseRouting();

        
        app.UseCors("AllowAny");

        app.UseMvc(routes =>
        {
            routes.Select().Expand().Filter().OrderBy().MaxTop(100).Count();
            routes.SetSerializeNullDynamicProperty(true);
            routes.MapODataServiceRoute("odata", "odata", GetEdmModel());

            routes.MapRoute(
                name: "base",
                template: "{controller}/{action=Index}/{id?}");                
        });


        app.UseSpa(spa =>
        {
            // To learn more about options for serving an Angular SPA from ASP.NET Core,
            // see https://go.microsoft.com/fwlink/?linkid=864501

            spa.Options.SourcePath = "ClientApp";

            if (env.IsDevelopment())
            {
                spa.UseProxyToSpaDevelopmentServer("http://localhost:4300");
                //spa.UseAngularCliServer(npmScript: "start");
            }
        });
    }


    private static IEdmModel GetEdmModel()
    {
        ODataModelBuilder builder = new ODataModelBuilder();

        EntityTypeConfiguration<DataItem> bookType = builder.EntityType<DataItem>();
        bookType.HasKey(c => c.__id);
        bookType.HasDynamicProperties(c => c.DynamicProperties);
        bookType.Property(_ => _.__id).IsOptional();

        var entity = builder.EntitySet<DataItem>("Entities");
        var funcGetEntity = entity.EntityType.Collection.Function("GetEntity").ReturnsCollectionFromEntitySet<DataItem>("Entities");
        funcGetEntity.Parameter<string>("entity");
        IEdmModel model = builder.GetEdmModel();            

        return model;
    }
}`

**Comment by marabooy** [comment]
@bonfi7 Could you share the generated csdl?

**Comment by bonfi7** [comment]
@marabooy What do you mean with "generated csdl"? 
I am not using Entity Framework, DataProvider execute SQL query(or with other providers) directly on the database.
To semplify the sample you can use: 
`	[EnableQuery]
	public IActionResult GetEntity(string entity)
	{            
		if (string.IsNullOrEmpty(entity))
		{
			return BadRequest();
		}
		var items = new List<DataItem>();

            items.Add(new DataItem
            {
            __id = 1,
            DynamicProperties = new Dictionary<string,object> {
                { "CustomerKey", 11056 },
			    {"GeographyKey", 10},
			    {"CustomerAlternateKey", "AW00011056"},
			    {"Title", null},
			    {"FirstName", "Michele"},
			    {"MiddleName", "L"},
			    {"LastName", "Nath"},
			    {"NameStyle", false},
			    {"BirthDate", "1953-04-03T00,00,00"},
			    {"MaritalStatus", "M"},
			    {"Suffix", null},
			    {"Gender", "F"},
			    {"EmailAddress", "michele19@adventure-works.com"},
			    {"YearlyIncome", 40000.0000},
			    {"TotalChildren", 3},
			    {"NumberChildrenAtHome", 0},
			    {"EnglishEducation", "Partial College"},
			    {"SpanishEducation", "Estudios universitarios (en curso)"},
			    {"FrenchEducation", "Baccalauréat"},
			    {"EnglishOccupation", "Skilled Manual"},
			    {"SpanishOccupation", "Obrero especializado"},
			    {"FrenchOccupation", "Technicien"},
			    {"HouseOwnerFlag", "1"},
			    {"NumberCarsOwned", 2},
			    {"AddressLine1", "5464 Janin Pl."},
			    {"AddressLine2", null},
			    {"Phone", "1 (11) 500 555-0178"},
			    {"DateFirstPurchase", "2005-08-29T00,00,00"},
                { "CommuteDistance", "5-10 Miles" }

        }
        });

			items.Add(new DataItem
			{
				__id = 1,
				DynamicProperties = new Dictionary<string, object> {
				{ "CustomerKey", 11056 },
				{"GeographyKey", 10},
				{"CustomerAlternateKey", "AW00011056"},
				{"Title", null},
				{"FirstName", "Michele"},
				{"MiddleName", "L"},
				{"LastName", "Nath"},
				{"NameStyle", false},
				{"BirthDate", "1953-04-03T00,00,00"},
				{"MaritalStatus", "M"},
				{"Suffix", null},
				{"Gender", "F"},
				{"EmailAddress", "michele19@adventure-works.com"},
				{"YearlyIncome", 1000.0000},
				{"TotalChildren", 3},
				{"NumberChildrenAtHome", 0},
				{"EnglishEducation", "Partial College"},
				{"SpanishEducation", "Estudios universitarios (en curso)"},
				{"FrenchEducation", "Baccalauréat"},
				{"EnglishOccupation", "Skilled Manual"},
				{"SpanishOccupation", "Obrero especializado"},
				{"FrenchOccupation", "Technicien"},
				{"HouseOwnerFlag", "1"},
				{"NumberCarsOwned", 2},
				{"AddressLine1", "5464 Janin Pl."},
				{"AddressLine2", null},
				{"Phone", "1 (11) 500 555-0178"},
				{"DateFirstPurchase", "2005-08-29T00,00,00"},
				{ "CommuteDistance", "5-10 Miles" }

		}
			});
			return Ok(items?.AsQueryable());
	}`

**Comment by marabooy** [comment]
Thanks for providing this. I noticed that the the query is `$filter=Quantity eq 300` which doesn't work but `$filter=Quantity eq 300f` works as it explicitly sends the type.

**Comment by marabooy** [comment]
@bonfi7 Is there a reason to not expose everything on the metadata? Exposing the types may help fix a lot of issues with the types since in the open types it may be hard to try and guess the types on the WebApi side as anything could be contained in the field as it doesn't stop a user from adding anything other type in one of the fields. e.g  `YearlyIncome` can be a string in the open type above.

**Comment by bonfi7** [comment]
@marabooy I know but I don’t know the model at design time. In my scenario user could add or edit entities at runtime writing the query in the GUI and the types are resolved in the fly at server side.

**Comment by marabooy** [comment]
In this case it seems that the Angular ui knows about the datatype, Not sure if you could use this to guess the type and generate the right query with the data type.

**Comment by dweeden** [comment]
@bonfi7 did you ever solve this?  i'm seeing the exact same behaviour within a very similar dynamic context using devexpress's dxDatagrid

**Comment by dweeden** [comment]
@xuzhg @marabooy should I open a new ticket for this considering it's still a problem or can it be reopened?
